language: java
jdk: "-openjdk11"
env:
  global:
  - CODECOV_TOKEN='9b3f4403-014a-4ea3-b09a-bc93708a17b8'
  - env='DEV'
after_success:
- bash <(curl -s https://codecov.io/bash)
services:
- postgresql
deploy:
  provider: heroku
  app: wax-deals
  on:
    branch: develop
  strategy: git
  api_key:
    secure: cRIzYn1oLvYWdWEsDSf5qJWx6FJlqQ0XNrs1FuZJEa8E/xm89C/4xKGwWk7H87z4C8dbOE6pvcvpj7pj5RZB9Q9TJiFyUuLWmdpCVVnigkNcRasJmktxVPsNqR17wfSV/K3SR3ktyC4Vh2tPbaolTFOXC4tKQ3t61CO5m8m1FTcgfnOsFfo9PEJA6ceDS+Gn9zQloe9/hq/FeEpl7iU/8eLoNgEvlwgOBaaJiCpF9Biob4h7o7KWUKYzgDUUYKffwoRdd1kP6RLigxzP/jwD3xV69evrwPKtL2dLdSBFEovSTlKr2ij1ysAi5vdWqZID2lEvxvvwKUGh0+QPV6QLXI7Zm0X85jcHJ9MjcEFk7lEFr/fiWp1egjJ7X+z5PAMkcw3kwZ76ZVVAWj5PgrqtIH0ymsJjypoVlIkYsjSkUW8SJfb0xH4JsISKT0sIFVw075gty9f44iO1oTrvxs7MY5WsZlWcrfC1fp/0vTRAo4N1XmSDQ3vUuzAO2Eaaz0VLBc0hj3I8ii+hjgvqkCey5aSJZT4sBn6XG/YQwa9JrBVdkVEb+CHJDiQywAPllelVzppQVNzRn5X4/phQ+qVbv+efX+qupWK2nZ9gpNxKaHD4dlZsNRCCs1O4e2kj89o7o8Vl8SintG+Hru1nU9y3RGYpmyBajnD4CWVlpXyoIug=
